version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # ignore:
    #   # Packages to ignore for updates
    #   - dependency-name: "eslint"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: "scope"
    # reviewers:
    #   - "your-github-username"  # Assign reviewer if needed
    # assignees:
    #   - "your-github-username"

  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 5
  #   # ignore:
  #   #   - dependency-name: "node" 
  #   labels:
  #     - "dependencies"
  #     - "docker"
  #   commit-message:
  #     prefix: "chore"
  #     prefix-development: "build"
  #     include: "scope"
  #   reviewers:
  #     - "your-github-username"
  #   assignees:
  #     - "your-github-username"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"

  # - package-ecosystem: "pip"
  #   directory: "/requirements"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 10
  #   labels:
  #     - "dependencies"
  #     - "python"
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope"
  #   reviewers:
  #     - "your-github-username"
  #   assignees:
  #     - "your-github-username"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"
    allow:
      - dependency-type: "direct"
